### ISSUE TITLE
Whose Copyright is it?

### ISSUE THREAD

**Issue by dl1ely** [cryogen-project/cryogen-markdown#1]
I planned to contribute a minimal README.md for this project (I know, not much needed), but i have no idea who is the copyright holder, @yogthos or @lacarmen . Same goes for cryogen-asciidoc.

Please advise.

**Comment by yogthos** [comment]
I suppose at @yogthos for both

**Comment by dl1ely** [comment]
Thanks. I will write a short README.

Dmitri Sotnikov notifications@github.com schrieb am Do., 29. Jan. 2015
19:42:

**Comment by yogthos** [comment]
great thanks!
