### ISSUE TITLE
Automatically numbered lists with nested code blocks 

### ISSUE THREAD

**Issue by willfurnass** [cryogen-project/cryogen-markdown#10]
I can't get this to render properly with `cryogen-core` 0.1.60 and `cryogen-markdown` 0.1.7.  Here's what I want to render:

```
Here's how you can run this example:
  
1.  Set up [SSH public-key authentication and a SSH Agent](https://debian-administration.org/article/530/SSH_with_authentication_key_instead_of_password) so
    Paramiko can SSH to a login node of your Grid Engine server without needing a password;
1.  Clone the GitHub Gist using [git](https://git-scm.com/):
    ```
    git clone https://gist.github.com/willfurnass/37bec522fea281bd325de421f755c10d paramiko_example
    cd paramiko example
    ```
1.  We now need to make sure the `paramiko` Python package is installed on your local machine.
    You could install it globally using your package manager...
```

I've tried various levels of indentation, backticks vs no backticks, blank lines vs no blank lines and either the `cd paramiko_example` line isn't included in the formatted code block or item numbering restarts for the third item in the numbered list.

For info, the above example renders fine in the online markdown-clj previewer.

**Comment by yogthos** [comment]
Hi,

Looks like this is likely a bug in [markdown-clj](https://github.com/yogthos/markdown-clj/). The easiest solution here is to swap it out for the [cryogen-flexmark](https://github.com/cryogen-project/cryogen-flexmark) plugin to see if it handles this case better.
