### ISSUE TITLE
Incorrect inline verbatim parsing in Markdown file

### ISSUE THREAD

**Issue by fest** [cryogen-project/cryogen-markdown#6]
I found that after being converted to `.html` file, all the inline code (or verbatim) parts which contain backslash (`\`) are not properly parsed (probably displayed in ascii code). For example: an `.md` file with following content

``` markdown
Replace all `$something...$` with `\(something...\)`: Find what: `\$(.*?)\$`  Replace with: `\\\(\1\\\)`
```

is converted to an `.html` file like (I copied directly from the generated html page)

``` html
Replace all $something...$ with &#40;something...&#41;: Find what: \$(.*?)\$ Replace with: &#92;&#40;\1&#92;&#41;
```

and by using `View Page Source` of the browser, I got

``` html
<div>

    <p>Replace all <code>$something...$</code> with <code>&amp;#40;something...&amp;#41;</code>: Find what: <code>\$&#40;.&#42;?&#41;\$</code>  Replace with: <code>&amp;#92;&amp;#40;\1&amp;#92;&amp;#41;</code></p>
</div>
```

But actually I think the backslash inside the `...` part should be kept unchanged instead of converting to some weird digits.

**Comment by yogthos** [comment]
That's expected behavior in the parser. Since things like `\` are also used as escape characters, they're converted into [html character codes](http://www.ascii.cl/htmlcodes.htm).

**Comment by fest** [comment]
@yogthos Thank you for your prompt reply. I am wondering whether it is possible to render html pages in a more intuitive way like Github favored markdown rendering. Any help would be appreciated.

**Comment by yogthos** [comment]
It would be a significant change to the parser to provide escaping for these characters without re-encoding them. If you really need this functionality, then you could swap in an alternative parser in your project, such as [cegdown](https://github.com/Raynes/cegdown) by creating your own version of the plugin. You'd just have to create a namespace that has the same API as seen [here](https://github.com/cryogen-project/cryogen-markdown/blob/master/src/cryogen_markdown/core.clj).

**Comment by fest** [comment]
@yogthos Thank you for your suggestions and I'll look into it.
